In [18]:
import pandas as pd
import numpy as np
data = pd.read_csv("/home/rsingh/lab_data/output/csv/patients.csv", nrows=5)
pd.set_option('display.max_columns', 200)

In [26]:
data['BIRTHDATE'] = pd.to_datetime(data['BIRTHDATE'])
data

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,fda9193a-4ffd-b3bc-e789-92c973aee4fe,2018-12-13,NaN,999-74-9259,NaN,NaN,NaN,Kimberlie352,Schamberger479,NaN,NaN,NaN,white,nonhispanic,F,Joliet Illinois US,269 McLaughlin Park,Chicago,Illinois,Cook County,17031,60628,41.982824,-87.884532,11468.76,0.00,478462
1,815a5aba-d663-3a4d-39b6-e0675923261c,2012-01-25,NaN,999-48-9088,NaN,NaN,NaN,Bulah832,Reinger292,NaN,NaN,NaN,white,nonhispanic,F,Arlington Heights Illinois US,250 Klein Walk Apt 4,Wheaton,Illinois,DuPage County,17043,60189,41.787686,-88.211954,18638.84,472.17,53131
2,02c6dc9a-d7bf-0e5d-5149-b8e033b146ea,2006-01-06,NaN,999-55-5935,S99986239,NaN,NaN,Tyra356,Miller503,NaN,NaN,NaN,white,nonhispanic,F,Caseyville Illinois US,624 Von Arcade Apt 42,Bourbonnais,Illinois,Kankakee County,17091,60914,41.111378,-87.863306,11262.69,52191.01,71607
3,d707860d-412a-0d9d-d253-b5fc224dc187,2008-04-07,NaN,999-69-7479,NaN,NaN,NaN,Hernán834,Cervantes583,NaN,NaN,NaN,white,hispanic,M,Mexico City Mexico City MX,1090 Nienow Orchard Apt 62,Berwyn,Illinois,Cook County,17031,60804,41.881579,-87.836019,2400.00,22768.83,1588
4,cf1b65f2-7064-7019-c78d-eea09346660f,2019-08-02,NaN,999-72-3368,NaN,NaN,NaN,Debra128,Keebler762,NaN,NaN,NaN,white,nonhispanic,F,Lake Forest Illinois US,503 Turcotte Alley,Cicero,Illinois,Cook County,17031,60804,41.823646,-87.804872,7294.85,0.00,35943

In [27]:
from anonympy.pandas.utils_pandas import available_methods
from anonympy.pandas import dfAnonymizer

In [28]:
anonym = dfAnonymizer(data)

In [29]:
anonym.anonymize({'FIRST': 'categorical_resampling',
                 'BIRTHDATE':'datetime_noise'})
anonym.to_df()

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,fda9193a-4ffd-b3bc-e789-92c973aee4fe,2018-07-15,NaN,999-74-9259,NaN,NaN,NaN,Kimberlie352,Schamberger479,NaN,NaN,NaN,white,nonhispanic,F,Joliet Illinois US,269 McLaughlin Park,Chicago,Illinois,Cook County,17031,60628,41.982824,-87.884532,11468.76,0.00,478462
1,815a5aba-d663-3a4d-39b6-e0675923261c,2011-11-23,NaN,999-48-9088,NaN,NaN,NaN,Bulah832,Reinger292,NaN,NaN,NaN,white,nonhispanic,F,Arlington Heights Illinois US,250 Klein Walk Apt 4,Wheaton,Illinois,DuPage County,17043,60189,41.787686,-88.211954,18638.84,472.17,53131
2,02c6dc9a-d7bf-0e5d-5149-b8e033b146ea,2005-05-10,NaN,999-55-5935,S99986239,NaN,NaN,Hernán834,Miller503,NaN,NaN,NaN,white,nonhispanic,F,Caseyville Illinois US,624 Von Arcade Apt 42,Bourbonnais,Illinois,Kankakee County,17091,60914,41.111378,-87.863306,11262.69,52191.01,71607
3,d707860d-412a-0d9d-d253-b5fc224dc187,2008-11-07,NaN,999-69-7479,NaN,NaN,NaN,Tyra356,Cervantes583,NaN,NaN,NaN,white,hispanic,M,Mexico City Mexico City MX,1090 Nienow Orchard Apt 62,Berwyn,Illinois,Cook County,17031,60804,41.881579,-87.836019,2400.00,22768.83,1588
4,cf1b65f2-7064-7019-c78d-eea09346660f,2019-09-03,NaN,999-72-3368,NaN,NaN,NaN,Hernán834,Keebler762,NaN,NaN,NaN,white,nonhispanic,F,Lake Forest Illinois US,503 Turcotte Alley,Cicero,Illinois,Cook County,17031,60804,41.823646,-87.804872,7294.85,0.00,35943